### ISSUE TITLE
Move repo to OpenStreetMap organisation?

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/gpx-updater#9]
@e-n-f would you be OK with us moving this repo to https://github.com/OpenStreetMap/ org?

This code is still used by https://gps-tile.openstreetmap.org/

**Comment by e-n-f** [comment]
@Firefishy Oh sure, please do. I am out of touch with the OSM world now and did not know if you were still using it.

**Comment by Firefishy** [comment]
@e-n-f Awesome. Could you use the Transfer tool listed at the bottom of https://github.com/e-n-f/gpx-updater/settings to change it to OpenStreetMap organisation.

**Comment by e-n-f** [comment]
@Firefishy I think you need to add me to the organization first. I got "You don’t have the permission to create public repositories on openstreetmap."

**Comment by Firefishy** [comment]
@e-n-f Try now..

**Comment by e-n-f** [comment]
Thanks! The repo is yours now: https://github.com/openstreetmap/gpx-updater
